export const DEFAULT_CONFIGURATION: Configuration = {
  schemaVersion: 1,
  apiToken: '',
  ankiUrl: 'http://localhost:8765',
  ankiProxyUrl: '',
  miningConfig: {
    deck: '',
    model: '',
    proxy: false,
    wordField: '',
    readingField: '',
    templateTargets: [],
  },
  blacklistConfig: {
    deck: '',
    model: '',
    proxy: false,
    wordField: '',
    readingField: '',
    templateTargets: [],
  },
  neverForgetConfig: {
    deck: '',
    model: '',
    proxy: false,
    wordField: '',
    readingField: '',
    templateTargets: [],
  },
  readonlyConfigs: [],
  contextWidth: 1,
  customPopupCSS: '',
  customWordCSS: '',
  showPopupOnHover: true,
  touchscreenSupport: false,
  disableFadeAnimation: false,
  showPopupKey: { key: 'Shift', code: 'ShiftLeft', modifiers: [] },
};
