export const DEFAULT_CONFIGURATION: Configuration = {
  ankiUrl: '127.0.0.1:8765',
  apiToken: '',
  blacklistDeckId: '',
  contextWidth: 1,
  customPopupCSS: '',
  customWordCSS: '',
  disableFadeAnimation: false,
  miningDeckId: '',
  neverForgetDeckId: '',
  schemaVersion: 1,
  showPopupOnHover: true,
  touchscreenSupport: false,
  showPopupKey: 'Shift',
};
